version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: '11:00'
      timezone: America/Toronto
    commit-message:
      prefix: GitHub Actions
    open-pull-requests-limit: 15

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: '11:00'
      timezone: America/Toronto
    commit-message:
      prefix: Go Modules
    open-pull-requests-limit: 15
