name: Checkmate-Evo - Checklist Checker
description: Automated checklist inspector for Pull Tequests
author: Marcus Couto - Forked from "Rory Quinn" at https://github.com/marcusvnac/checkmate-evo

inputs:
  github_token:
    description: Required for automated checklist comments.
  paths:
    description: Mapping of paths to automated checklists to create.
  preamble:
    description: Custom message to show in the automated checklist comment.
  version:
    description: Release version of checkmate to run.
runs:
  using: node16
  main: index.js
branding:
  icon: check-square
  color: green
